config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations" 
  }  
  root   'static_pages#home'
  resources :users 
  resources :clients do
    member do
      get 'new_report'
      post 'create_new_report', to: 'reports#create'
    end
    # resources :reports, only: [ :new, :create]
  end
  resources :reports, only: [:index, :show, :edit, :update, :destroy]

  

  # post 'reports', to: 'report#create'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :reports
  has_many :users, through: :reports
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :phone, presence: true, length: { maximum: 20}
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :admin_user, only: [:destroy, :update]

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    #@reports = @client.reports.paginate(page: params[:page])
  end
  
  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:info] = 'Cliente aggiunto.'
      redirect_to @client
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @client.update(client_params)
      flash[:success] = 'Cliente aggiornato'
      redirect_to @client
    else
      redner 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    Client.find(params[:id]).destroy
    flash[:success] = 'Cliente rimosso'
    redirect_to clients_url, status: :see_other
  end
  
  private

  def client_params
    params.require(:client).permit(:name, :email, :phone, :address)
  end

  def current_client
    @current_client = Client.find(params[:id])
  end
  
  def admin_user
    current_user.admin? 
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with model:@client do |f| %>
  <%= f.label :name, "Nome" %>
  <%= f.text_field :name, class: 'form-control' %>
      
  <%= f.label :email, "Email" %>
  <%= f.email_field :email, class: 'form-control' %>
      
  <%= f.label :phone, "Reacpito telefonico" %>
  <%= f.text_field :phone, class: 'form-control' %>
      
  <%= f.label :address, "Indirizzo" %>
  <%= f.text_field :address, class: 'form-control' %>
  <br>
  <%= f.submit "Conferma", class: "btn btn-primary" %>
<% end %>

app/views/clients/edit.html.erb
<h1>Aggiorna dati cliente</h1>

<%= render 'form' %>

app/views/clients/index.html.erb
<h1>Tutti clienti:</h1>
<ul class="list-group">
  <% @clients.each do |client| %>
    <li class="list-group-item">  
      <%= link_to "Nome cliente: #{client.name}", client_path( client ), 
                  class:"link-success" %>
      <%= "Indirizzo: #{client.address}" %>
    </li>
  <% end %>
</ul>

app/views/clients/new.html.erb
<h1>Nuovo cliente</h1>

<%= render 'form' %>

app/views/clients/new_report.html.erb
<%= form_with url: create_new_report_client_path, method: :post do |f| %>
  
  <%= f.label :description, "Lavoro svolto" %>
  <%= f.text_area :description, class: 'form-control' %> 

  <%= f.label :material, "Materiale usato" %>
  <%= f.text_field :material, class: 'form-control' %>

  <%= f.label :hours, "Ore lavorate" %>
  <%= f.number_field :hours, class: 'form-control' %>
  
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit "Conferma", class: "btn btn-primary" %>
<% end %>

app/views/clients/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @client.name %>
      </h1>
      <h6>
        <%= "Email: #{@client.email}" %>
      </h6>
      <h6>
        <%= "Recapito telefonico: #{@client.phone}" %>
      </h6>
      <h6>
      <%= "Indirizzo: #{@client.address}" %>
      </h6>
      <br>
      <%= link_to "Aggiungi rapportino",  new_report_client_path,
                   class:"btn btn-primary" %>
      <br>
      <br>
      <%= link_to "Aggiorna dati cliente", edit_client_path( @client ),
                   class:"btn btn-primary" %>
      <br>
      <br>
    </section>
  <div class="col-md-8">
    <% if @client.reports.any? %>
      <h3>Lavori svolti per il cliente (<%= @client.reports.count %>)</h3>
      <ul class="list-group">
      <% @client.reports.each do |report| %>
        <li class="list-group-item">  
          <%="Nome cliente: #{report.client.name}"%>
          <%= link_to  "Data:#{report.created_at.mday}/#{report.created_at.month}/#{report.created_at.year}",
                               report_path(report)  %>
        </li>
      <% end %>
      </ul>
    <% end %>
  </div>
</div>