config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations" 
  }  
  root   'static_pages#home'
  resources :users 
  resources :clients do
    member do
      get 'new_report'
      post 'create_new_report', to: 'reports#create'
    end
    # resources :reports, only: [ :new, :create]
  end
  resources :reports, only: [:index, :show, :edit, :update, :destroy]

  

  # post 'reports', to: 'report#create'
end

app/models/report.rb
class Report < ApplicationRecord
  require 'csv'

  belongs_to :user
  belongs_to :client
  
  def self.to_csv
    CSV.generate do |csv|
        attributes = %w{ Nome_cliente Data Indirizzo_cliente Lavoratore Lavoro_svolto Materiale_usato Ore }
        csv << attributes
        all.each do |report|
        # csv << report.attributes.merge(report.client.attributes).values_at(*attributes)
        csv << [ report.client.name, report.created_at, 
          report.client.address, report.user.name, 
          report.description, report.material, 
          report.hours ]
      end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    if user_signed_in?
      if current_user.admin?    
        @reports = Reports.all.order(:client_id)
      else
        @reports = Report.where(user_id: current_user.id).order(:client_id)
      end
      respond_to do |format|
        format.html
        format.csv { send_data Report.to_csv, filename: "reports-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv" }
      end
    else
      redirect_to  new_user_session_path
    end
  end

  def show
    @report = Report.find(params[:id])
    @client = @report.client
    @user = @report.user
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    if @report.save!
      flash[:info] = 'Raportino aggiunto'
      redirect_to @report
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @report.update(report_params)
      flash[:success] = 'Raportino aggiornato'
      redirect_to @report
    else
      redner 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    if current_user.admin? 
        Report.find(params[:id]).destroy
        flash[:success] = 'Raportino cancelatto'
        redirect_to reports_url, status: :see_other
    end
  end

  private

  def report_params
    # changed name of key for easier creation
    params['client_id'] = params['id']
    params.delete('id')

    params.permit(:description, :material, :hours, :user_id, :client_id)
  end

  def current_report
    @current_report = Report.find(params[:id])
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with model:@report do |f| %>
  
  <%= f.label :description, "Lavoro svolto" %>
  <%= f.text_area :description, class: 'form-control' %> 

  <%= f.label :material, "Materiale usato" %>
  <%= f.text_field :material, class: 'form-control' %>

  <%= f.label :hours, "Ore lavorate" %>
  <%= f.number_field :hours, class: 'form-control' %>
  
  <%= f.hidden_field :user_id, value: current_user.id %>

  
  <%= f.submit "Conferma", class: "btn btn-primary" %>
<% end %>

app/views/reports/edit.html.erb
<h1>Aggiorna dati rapportino</h1>

<%= render 'form' %>
<br>

app/views/reports/index.html.erb
<h1>Tutti raportini:</h1>
<ul class="list-group">
  <% @reports.each do |report| %>
    <li class="list-group-item">  
      <%="Nome cliente: #{report.client.name}"%>
      <%= link_to  "Data:#{report.created_at.mday}/#{report.created_at.month}/#{report.created_at.year}",
                           report_path(report), class:"link-success" %>
    </li>
  <% end %>
</ul>
<br>
<%= link_to "Esporta come csv", reports_path(format: 'csv'), class:"btn btn-success" %>

app/views/reports/new.html.erb
<h1>Nuovo rapportino</h1>

<%= render 'form' %>

app/views/reports/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= "Lavoratore: #{@report.user.name}" %>
      </h1>
      <ul class="list-group">
        <li class="list-group-item">
          <h5>Lavoro svolto: </h5>
          <%=  @report.description %>
        </li>
        <li class="list-group-item">
          <h5>Materiale usato: </h5>
          <%= @report.material %>
        </li>
        <li class="list-group-item">
          <h5>Ore lavorate: </h5>
          <%= @report.hours %>
        </li>
        <li class="list-group-item">
          <h5>Nome Clietne: </h5>
          <%= @client.name %>
        </li>
        <li class="list-group-item">
          <h5>Indirizzo cliente: </h5>
          <%= @client.address %>
        </li>
        <li class="list-group-item">
          <h5>Data: </h5>
          <%= "#{@report.created_at.mday}/#{@report.created_at.month}/#{@report.created_at.year}" %>
        </li>
      </ul>
        <br>
      <%= link_to "Aggiorna dati raportino", edit_report_path(@report),
                   class:"btn btn-primary" %>
    </section>
</div>