config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations" 
  }  
  root   'static_pages#home'
  resources :users 
  resources :clients do
    member do
      get 'new_report'
      post 'create_new_report', to: 'reports#create'
    end
    # resources :reports, only: [ :new, :create]
  end
  resources :reports, only: [:index, :show, :edit, :update, :destroy]

  

  # post 'reports', to: 'report#create'
end

app/views/layouts/_alerts.html.erb
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="footer" id="footer">
    <small>
    App creata da <a href="https://github.com/IvanMi95">Ivan Milanovic</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Rapportini App", root_path, class:"navbar-brand" %>

    </button>
    <div class="navbar-" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Clienti", clients_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to"Nuovo cliente", new_client_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to"Rapportini", reports_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %> 
          <li class="nav-item">
            <%= link_to current_user.name, user_path(current_user),
                        class:"nav-link" %>
          </li>
          <li>
             <%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete,class:"btn btn-danger btn-sm"
      ) %>
          </li>
        <% else %>
          <li>
            <%= link_to "Log In ", new_user_session_path, 
                         class:"btn btn-success btn-sm" %>
          </li>
          <li>
            <%= link_to"Sign Up", new_user_registration_path,
                        class:"btn btn-warning btn-sm"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/alerts' %>
    <div class="container">
    
    <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>